### ISSUE TITLE
 mbtiles file can't work in  nutiteq/hellomap3d-ios

### ISSUE THREAD

**Issue by WiFiInHand** [HTML24/mbtiles-generator#1]
hi, i use your project to create a mbtiles file, but the map can't be show in nutiteq/hellomap3d-ios. do you know why?

**Comment by dvaeversted** [comment]
The output files have been tested with the MapBox iOS SDK https://github.com/mapbox/mapbox-ios-sdk/
And the nutiteq android SDK (old version): https://github.com/nutiteq/hellomap3d

Without any specific error output, i am unfortunately unable to assist any further with fixing any problems, it should probably be directed at nutiteq/hellomap3d-ios, seeing as it works in other SDK's.

**Comment by WiFiInHand** [comment]
thanks your replay. I change the parameter to test the map file, It can's show. but I managed to show map created by MobAC. maybe the sdk or ios's problem.

**Comment by dvaeversted** [comment]
Came to think of it, have you tried with the latest master revision ?
